/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc.h"

int *
factorial_1_svc(s *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	 int ans=1;
	 int i=1;
	 for(int i=1;i<=argp->a;i++)
	 {
	 	ans*=i;
	 }
	 
	 result=ans;
	 //aaa
	 printf("client sent %d",argp->a);

	return &result;
}
