/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc.h"

float *
feettometer_1_svc(s *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	int feet=argp->a;
	result=feet*0.3048;

	return &result;
}
